export interface Package {
  id: string;
  name: string;
  price: number;
  originalPrice: number;
  discount: number;
  testsCount: number;
  tests: string[];
  description: string;
  sampleType: string;
  fastingRequired: boolean;
  reportTime: string;
  popular: boolean;
  category: string;
}

export const mockPackages: Package[] = [
  {
    id: "1",
    name: "Full Body Checkup",
    price: 2499,
    originalPrice: 3999,
    discount: 37,
    testsCount: 85,
    tests: ["CBC", "Lipid Profile", "Liver Function", "Kidney Function", "Thyroid Profile", "Diabetes Screening"],
    description: "Comprehensive health screening covering all major body functions including complete blood count, lipid profile, liver and kidney function tests, thyroid screening, and diabetes markers.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: true,
    category: "Full Body Packages"
  },
  {
    id: "2",
    name: "Diabetes Screening",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    testsCount: 6,
    tests: ["Fasting Blood Sugar", "HbA1c", "Post Meal Blood Sugar", "Insulin Levels", "Random Blood Sugar", "Average Blood Glucose"],
    description: "Complete diabetes panel for monitoring and diagnosis including fasting sugar, HbA1c, and insulin levels.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: true,
    category: "Diabetes Tests"
  },
  {
    id: "3",
    name: "Thyroid Profile",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    testsCount: 3,
    tests: ["TSH", "T3", "T4"],
    description: "Complete thyroid function evaluation measuring TSH, T3, and T4 levels to assess thyroid health.",
    sampleType: "Blood",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: true,
    category: "Thyroid Tests"
  },
  {
    id: "4",
    name: "Comprehensive Gold",
    price: 3499,
    originalPrice: 5999,
    discount: 42,
    testsCount: 100,
    tests: ["All Full Body tests", "Vitamin D", "Vitamin B12", "Iron Studies", "Cancer Markers", "Advanced Cardiac Profile"],
    description: "Most comprehensive health checkup with all essential parameters including vitamins, minerals, and cancer markers.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "48 hours",
    popular: true,
    category: "Full Body Packages"
  },
  {
    id: "5",
    name: "Women's Health Package",
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    testsCount: 45,
    tests: ["Complete Blood Count", "Thyroid Profile", "Vitamin D", "Iron Studies", "Hormone Panel", "Pap Smear"],
    description: "Comprehensive health package designed specifically for women's health needs.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: false,
    category: "Women's Health"
  },
  {
    id: "6",
    name: "Heart Health Checkup",
    price: 1599,
    originalPrice: 2499,
    discount: 36,
    testsCount: 25,
    tests: ["Lipid Profile", "ECG", "Cardiac Enzymes", "CRP", "Homocysteine", "Troponin"],
    description: "Complete cardiac health evaluation including lipid profile, ECG, and cardiac markers.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: false,
    category: "Heart Health"
  },
  {
    id: "7",
    name: "Complete Blood Count (CBC)",
    price: 599,
    originalPrice: 899,
    discount: 33,
    testsCount: 4,
    tests: ["Hemoglobin", "Total WBC Count", "RBC Count", "Platelet Count"],
    description: "Basic blood test to evaluate overall health and detect disorders like anemia and infection.",
    sampleType: "Blood",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: false,
    category: "Full Body Packages"
  },
  {
    id: "8",
    name: "Liver Function Test",
    price: 699,
    originalPrice: 1099,
    discount: 36,
    testsCount: 12,
    tests: ["SGOT", "SGPT", "Bilirubin", "Alkaline Phosphatase", "Total Protein", "Albumin", "Globulin", "A/G Ratio"],
    description: "Comprehensive liver function assessment to check liver health and detect liver diseases.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: false,
    category: "Liver & Kidney Tests"
  },
  {
    id: "9",
    name: "Kidney Function Test",
    price: 649,
    originalPrice: 999,
    discount: 35,
    testsCount: 10,
    tests: ["Creatinine", "Blood Urea Nitrogen", "Uric Acid", "Electrolytes", "Sodium", "Potassium", "Chloride"],
    description: "Complete kidney function evaluation to assess kidney health and detect kidney disorders.",
    sampleType: "Blood & Urine",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: false,
    category: "Liver & Kidney Tests"
  },
  {
    id: "10",
    name: "Vitamin D Test",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    testsCount: 1,
    tests: ["25-Hydroxy Vitamin D"],
    description: "Measures vitamin D levels to assess bone health and immune function.",
    sampleType: "Blood",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: false,
    category: "Vitamins & Minerals"
  },
  {
    id: "11",
    name: "Vitamin B12 Test",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    testsCount: 1,
    tests: ["Vitamin B12"],
    description: "Measures vitamin B12 levels to detect deficiency and assess neurological health.",
    sampleType: "Blood",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: false,
    category: "Vitamins & Minerals"
  },
  {
    id: "12",
    name: "Iron Studies",
    price: 999,
    originalPrice: 1599,
    discount: 38,
    testsCount: 5,
    tests: ["Serum Iron", "TIBC", "Transferrin Saturation", "Ferritin", "Hemoglobin"],
    description: "Complete iron profile to diagnose iron deficiency anemia and iron overload disorders.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: false,
    category: "Vitamins & Minerals"
  },
  {
    id: "13",
    name: "Men's Health Package",
    price: 1899,
    originalPrice: 2799,
    discount: 32,
    testsCount: 42,
    tests: ["Complete Blood Count", "Lipid Profile", "Liver Function", "Kidney Function", "Testosterone", "PSA"],
    description: "Comprehensive health package designed specifically for men's health needs.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: false,
    category: "Men's Health"
  },
  {
    id: "14",
    name: "Fever Panel",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    testsCount: 15,
    tests: ["CBC", "Dengue NS1", "Dengue IgG/IgM", "Malaria", "Typhoid", "Blood Culture", "Urine Culture"],
    description: "Comprehensive fever investigation panel to identify causes of prolonged fever.",
    sampleType: "Blood & Urine",
    fastingRequired: false,
    reportTime: "48 hours",
    popular: false,
    category: "Fever & Infection Tests"
  },
  {
    id: "15",
    name: "Allergy Panel",
    price: 2499,
    originalPrice: 3999,
    discount: 38,
    testsCount: 35,
    tests: ["Food Allergens", "Pollen Allergens", "Dust Mites", "Pet Dander", "Mold Spores"],
    description: "Comprehensive allergy testing panel to identify specific allergens causing reactions.",
    sampleType: "Blood",
    fastingRequired: false,
    reportTime: "48 hours",
    popular: false,
    category: "Allergy Tests"
  },
  {
    id: "16",
    name: "Lipid Profile",
    price: 749,
    originalPrice: 1199,
    discount: 38,
    testsCount: 8,
    tests: ["Total Cholesterol", "HDL", "LDL", "VLDL", "Triglycerides", "Cholesterol/HDL Ratio", "LDL/HDL Ratio"],
    description: "Complete cholesterol and lipid assessment for heart health evaluation.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: false,
    category: "Heart Health"
  },
  {
    id: "17",
    name: "HbA1c Test",
    price: 599,
    originalPrice: 999,
    discount: 40,
    testsCount: 1,
    tests: ["Glycated Hemoglobin (HbA1c)"],
    description: "3-month average blood sugar level test for diabetes monitoring and diagnosis.",
    sampleType: "Blood",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: false,
    category: "Diabetes Tests"
  },
  {
    id: "18",
    name: "Advanced Thyroid Panel",
    price: 1499,
    originalPrice: 2299,
    discount: 35,
    testsCount: 5,
    tests: ["TSH", "T3", "T4", "Free T3", "Free T4"],
    description: "Advanced thyroid function tests including free hormones for comprehensive thyroid assessment.",
    sampleType: "Blood",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: false,
    category: "Thyroid Tests"
  },
  {
    id: "19",
    name: "Basic Metabolic Panel",
    price: 899,
    originalPrice: 1399,
    discount: 36,
    testsCount: 8,
    tests: ["Glucose", "Calcium", "Sodium", "Potassium", "CO2", "Chloride", "BUN", "Creatinine"],
    description: "Basic metabolic panel to assess overall body metabolism and organ function.",
    sampleType: "Blood",
    fastingRequired: true,
    reportTime: "24 hours",
    popular: false,
    category: "Full Body Packages"
  },
  {
    id: "20",
    name: "COVID-19 RT-PCR",
    price: 699,
    originalPrice: 999,
    discount: 30,
    testsCount: 1,
    tests: ["COVID-19 RT-PCR"],
    description: "RT-PCR test for COVID-19 detection with results in 24 hours.",
    sampleType: "Nasal Swab",
    fastingRequired: false,
    reportTime: "24 hours",
    popular: false,
    category: "Fever & Infection Tests"
  }
];

export const categories = [
  "Full Body Packages",
  "Diabetes Tests",
  "Thyroid Tests",
  "Liver & Kidney Tests",
  "Vitamins & Minerals",
  "Women's Health",
  "Men's Health",
  "Fever & Infection Tests",
  "Heart Health",
  "Allergy Tests"
];
